[build] build ex-submodules in a build/ subdirectory
This keeps the local repo cleaner by grouping all the build artifacts in a single subdir of the tree.

Refactor a bunch of boilerplate code.

diff --git a/contrib/make_libevent b/contrib/make_libevent
--- a/contrib/make_libevent
+++ b/contrib/make_libevent
@@ -5,30 +5,23 @@ set -e
 here=$(dirname $(realpath "$0" 2> /dev/null || grealpath "$0"))
 . "$here"/base.sh || (echo "Could not source contrib/base.sh" && exit 1)
 
-pkgname="libevent"
-info "Building $pkgname..."
+setup_pkg "libevent" "https://github.com/libevent/libevent.git" "4c908dde58ef780eeefcc9df4db3063ca62ea862" $here
 
-pushd "$here"
-git clone  https://github.com/libevent/libevent.git
-
-pushd "$here"/$pkgname || fail "Could not chdir to $here/$pkgname"
-git checkout 4c908dde58ef780eeefcc9df4db3063ca62ea862
 if ! [ -x configure ] ; then
     ./autogen.sh || fail "Could not configure $pkgname"
 fi
 if ! [ -r config.status ] ; then
     ./configure \
         $AUTOCONF_FLAGS \
-        --prefix="$here/$pkgname/dist" \
+        --prefix="$pkgbuilddir/dist" \
         --disable-shared \
         --enable-static \
         --with-pic \
         --disable-samples \
         --disable-libevent-regress \
-        CPPFLAGS=-I"$here"/openssl/dist \
-        LDFLAGS=-L"$here"/openssl/dist || fail "Could not configure $pkgname"
+        CPPFLAGS=-I"$parentbuilddir"/openssl/dist \
+        LDFLAGS=-L"$parentbuilddir"/openssl/dist || fail "Could not configure $pkgname"
 fi
 make -j$WORKER_COUNT || fail "Could not build $pkgname"
 make install || fail "Could not install $pkgname"
-popd
-popd
+popd_pkg
diff --git a/contrib/make_secp b/contrib/make_secp
--- a/contrib/make_secp
+++ b/contrib/make_secp
@@ -5,12 +5,8 @@ set -e
 here=$(dirname $(realpath "$0" 2> /dev/null || grealpath "$0"))
 . "$here"/base.sh || (echo "Could not source contrib/base.sh" && exit 1)
 
-pkgname="secp256k1"
-echo "Building $pkgname..."
+setup_pkg "secp256k1" "https://github.com/Bitcoin-ABC/secp256k1.git" "master" $here
 
-pushd "$here"
-git clone --depth 1 https://github.com/Bitcoin-ABC/secp256k1.git
-pushd "$here"/$pkgname || fail "Could not chdir to $here/$pkgname"
 if ! [ -x configure ] ; then
     echo "libsecp256k1_la_LDFLAGS = -no-undefined" >> Makefile.am
     echo "LDFLAGS = -no-undefined" >> Makefile.am
@@ -19,7 +15,7 @@ fi
 if ! [ -r config.status ] ; then
     ./configure \
         $AUTOCONF_FLAGS \
-        --prefix="$here/$pkgname/dist" \
+        --prefix="$pkgbuilddir/dist" \
         --enable-module-recovery \
         --enable-experimental \
         --enable-module-ecdh \
@@ -32,10 +28,9 @@ if ! [ -r config.status ] ; then
 fi
 make -j$WORKER_COUNT || fail "Could not build $pkgname"
 make install || fail "Could not install $pkgname"
-. "$here/$pkgname/dist/lib/libsecp256k1.la"
-host_strip "$here/$pkgname/dist/lib/$dlname"
-cp -fpv "$here/$pkgname/dist/lib/$dlname" "$here/../electroncash/." || fail "Could not copy the $pkgname binary to its destination"
+. "$pkgbuilddir/dist/lib/libsecp256k1.la"
+host_strip "$pkgbuilddir/dist/lib/$dlname"
+cp -fpv "$pkgbuilddir/dist/lib/$dlname" "$here/../electroncash/." || fail "Could not copy the $pkgname binary to its destination"
 info "$dlname has been placed in the 'electroncash' folder."
-popd
-popd
-rm -Rf "$here"/secp256k1
+popd_pkg
+rm -Rf "$pkgbuilddir"
diff --git a/contrib/make_tor b/contrib/make_tor
--- a/contrib/make_tor
+++ b/contrib/make_tor
@@ -5,14 +5,8 @@ set -e
 here=$(dirname $(realpath "$0" 2> /dev/null || grealpath "$0"))
 . "$here"/base.sh || (echo "Could not source contrib/base.sh" && exit 1)
 
-pkgname="tor"
-info "Building $pkgname..."
+setup_pkg "tor" "https://github.com/EchterAgo/tor.git" "a08e549261b3dba0010e3238c9706b98a3840cda" $here
 
-pushd "$here"
-git clone https://github.com/EchterAgo/tor.git
-
-pushd "$here"/$pkgname || fail "Could not chdir to $here/$pkgname"
-git checkout a08e549261b3dba0010e3238c9706b98a3840cda
 LDFLAGS="-s"
 EXTRA_FLAGS=""
 if [ "$BUILD_TYPE" = "windows" ] ; then
@@ -27,14 +21,14 @@ fi
 if ! [ -r config.status ] ; then
     ./configure \
         $AUTOCONF_FLAGS \
-        --prefix="$here/$pkgname/dist" \
+        --prefix="$pkgbuilddir/dist" \
         --disable-system-torrc \
         --disable-manpage \
         --disable-html-manual \
         --disable-asciidoc \
-        --enable-static-libevent --with-libevent-dir=$here/libevent/dist \
-        --enable-static-openssl --with-openssl-dir=$here/openssl/dist \
-        --enable-static-zlib --with-zlib-dir=$here/zlib/dist \
+        --enable-static-libevent --with-libevent-dir=$parentbuilddir/libevent/dist \
+        --enable-static-openssl --with-openssl-dir=$parentbuilddir/openssl/dist \
+        --enable-static-zlib --with-zlib-dir=$parentbuilddir/zlib/dist \
         --disable-systemd \
         --disable-lzma \
         --disable-zstd \
@@ -51,11 +45,10 @@ binary="tor"
 if [ "$BUILD_TYPE" = "wine" ] ; then
     binary="tor.exe"
 fi
-host_strip "$here/$pkgname/dist/bin/$binary"
+host_strip "$pkgbuilddir/dist/bin/$binary"
 mkdir -p "$here/../electroncash/tor/bin"
-cp -fpv "$here/$pkgname/dist/bin/$binary" "$here/../electroncash/tor/bin/." || fail "Could not copy the $pkgname binary to its destination"
-$SHA256_PROG "$here/$pkgname/dist/bin/$binary"
+cp -fpv "$pkgbuilddir/dist/bin/$binary" "$here/../electroncash/tor/bin/." || fail "Could not copy the $pkgname binary to its destination"
+$SHA256_PROG "$pkgbuilddir/dist/bin/$binary"
 info "$binary has been placed in the 'electroncash' folder."
-popd
-popd
+popd_pkg
 rm -Rf "$here"/tor
diff --git a/contrib/make_zbar b/contrib/make_zbar
--- a/contrib/make_zbar
+++ b/contrib/make_zbar
@@ -5,14 +5,8 @@ set -e
 here=$(dirname $(realpath "$0" 2> /dev/null || grealpath "$0"))
 . "$here"/base.sh || (echo "Could not source contrib/base.sh" && exit 1)
 
-pkgname="zbar"
-info "Building $pkgname..."
+setup_pkg "zbar" "https://github.com/mchehab/zbar" "c7d9809b0b49e81fd86a48e9d1bc3c7db8c50bbd" $here
 
-pushd "$here"
-git clone https://github.com/mchehab/zbar
-
-pushd "$here"/$pkgname || fail "Could not chdir to $here/$pkgname"
-git checkout c7d9809b0b49e81fd86a48e9d1bc3c7db8c50bbd
 if [ "$BUILD_TYPE" = "wine" ] ; then
     echo "libzbar_la_LDFLAGS += -Wc,-static" >> zbar/Makefile.am
     echo "LDFLAGS += -Wc,-static" >> Makefile.am
@@ -23,7 +17,7 @@ fi
 if ! [ -r config.status ] ; then
     ./configure \
         $AUTOCONF_FLAGS \
-        --prefix="$here/$pkgname/dist" \
+        --prefix="$pkgbuilddir/dist" \
         --with-x=no \
         --enable-pthread=no \
         --enable-doc=no \
@@ -41,10 +35,9 @@ if ! [ -r config.status ] ; then
 fi
 make -j$WORKER_COUNT || fail "Could not build $pkgname"
 make install || fail "Could not install $pkgname"
-. "$here/$pkgname/dist/lib/libzbar.la"
-host_strip "$here/$pkgname/dist/lib/$dlname"
-cp -fpv "$here/$pkgname/dist/lib/$dlname" "$here/../electroncash/." || fail "Could not copy the $pkgname binary to its destination"
+. "$pkgbuilddir/dist/lib/libzbar.la"
+host_strip "$pkgbuilddir/dist/lib/$dlname"
+cp -fpv "$pkgbuilddir/dist/lib/$dlname" "$here/../electroncash/." || fail "Could not copy the $pkgname binary to its destination"
 info "$dlname has been placed in the 'electroncash' folder."
-popd
-popd
-rm -Rf "$here"/zbar
+popd_pkg
+rm -Rf "$pkgbuilddir"
diff --git a/contrib/make_zlib b/contrib/make_zlib
--- a/contrib/make_zlib
+++ b/contrib/make_zlib
@@ -5,16 +5,10 @@ set -e
 here=$(dirname $(realpath "$0" 2> /dev/null || grealpath "$0"))
 . "$here"/base.sh || (echo "Could not source contrib/base.sh" && exit 1)
 
-pkgname="zlib"
-info "Building $pkgname..."
+setup_pkg "zlib" "https://github.com/madler/zlib.git" "cacf7f1d4e3d44d871b605da3b647f07d718623f" $here
 
-pushd "$here"
-git clone https://github.com/madler/zlib.git
-
-pushd "$here"/$pkgname || fail "Could not chdir to $here/$pkgname"
-git checkout cacf7f1d4e3d44d871b605da3b647f07d718623f
 if [ "$BUILD_TYPE" = "wine" ] ; then
-    PREFIXDIR="$here/$pkgname/dist"
+    PREFIXDIR="$pkgbuilddir/dist"
     make -j$WORKER_COUNT -fwin32/Makefile.gcc \
         PREFIX="${GCC_TRIPLET_HOST}-" \
         BINARY_PATH="$PREFIXDIR/bin" \
@@ -24,10 +18,9 @@ if [ "$BUILD_TYPE" = "wine" ] ; then
 else
     if ! [ -r config.status ] ; then
         ./configure \
-            --prefix="$here/$pkgname/dist" || fail "Could not configure $pkgname"
+            --prefix="$pkgbuilddir/dist" || fail "Could not configure $pkgname"
     fi
     make -j$WORKER_COUNT || fail "Could not build $pkgname"
     make install || fail "Could not install $pkgname"
 fi
-popd
-popd
+popd_pkg
