rename electrumabc package
Test Plan:

run from source, build the release files and test them

diff --git a/contrib/make_tor b/contrib/make_tor
--- a/contrib/make_tor
+++ b/contrib/make_tor
@@ -46,9 +46,9 @@ if [ "$BUILD_TYPE" = "wine" ] ; then
     binary="tor.exe"
 fi
 host_strip "$pkgbuilddir/dist/bin/$binary"
-mkdir -p "$here/../electroncash/tor/bin"
-cp -fpv "$pkgbuilddir/dist/bin/$binary" "$here/../electroncash/tor/bin/." || fail "Could not copy the $pkgname binary to its destination"
+mkdir -p "$here/../electrumabc/tor/bin"
+cp -fpv "$pkgbuilddir/dist/bin/$binary" "$here/../electrumabc/tor/bin/." || fail "Could not copy the $pkgname binary to its destination"
 $SHA256_PROG "$pkgbuilddir/dist/bin/$binary"
-info "$binary has been placed in the 'electroncash' folder."
+info "$binary has been placed in the 'electrumabc' folder."
 popd_pkg
 rm -Rf "$here"/tor
diff --git a/contrib/osx/make_osx b/contrib/osx/make_osx
--- a/contrib/osx/make_osx
+++ b/contrib/osx/make_osx
@@ -199,7 +199,7 @@ verify_hash $BUILDDIR/libusb/1.0.21/lib/libusb-1.0.dylib d147e7382dfa676d93e8b17
 cp -fp $BUILDDIR/libusb/1.0.21/lib/libusb-1.0.dylib contrib/osx || fail "Could not copy libusb"
 
 # Build ZBar
-contrib/make_zbar && mv -vf electroncash/libzbar.0.dylib contrib/osx/. || fail "Could not build ZBar"
+contrib/make_zbar && mv -vf electrumabc/libzbar.0.dylib contrib/osx/. || fail "Could not build ZBar"
 
 info "Building libsecp256k1"
 
@@ -279,7 +279,7 @@ if ((DARWIN_VER >= 18 && FORCE_MOJAVE_DARK)); then
 fi
 
 # Sign the Tor binary separately
-DoCodeSignMaybe "tor binary" "dist/${PACKAGE}.app/Contents/MacOS/electroncash/tor/bin/tor" "$APP_SIGN"
+DoCodeSignMaybe "tor binary" "dist/${PACKAGE}.app/Contents/MacOS/electrumabc/tor/bin/tor" "$APP_SIGN"
 # Finally, codesign the whole thing
 DoCodeSignMaybe ".app bundle" "dist/${PACKAGE}.app" "$APP_SIGN"
 
