mac build: git clone pyinstaller to allow using custom commits
This allows more freedom than using releases from PyPI.
(atm there is no released version that fixes pyinstaller/pyinstaller#6701 )
Also, we now build the pyinstaller bootloader, just like in the windows build:
one fewer binary blob to trust.

Backport of https://github.com/spesmilo/electrum/commit/3bae7dfd903f86f8637ea185adca2a24d520205b#

diff --git a/contrib/osx/make_osx b/contrib/osx/make_osx
--- a/contrib/osx/make_osx
+++ b/contrib/osx/make_osx
@@ -1,9 +1,13 @@
 #!/bin/bash
 
-build_dir=$(dirname "$0")
+build_dir="$(dirname "$(realpath "$0")")"
 test -n "$build_dir" -a -d "$build_dir" || (echo "Cannot determine build dir. FIXME!" && exit 1)
+CACHEDIR="$build_dir/.cache"
+
+mkdir -p "$CACHEDIR"
 
 . "$build_dir"/../base.sh # functions we use below
+
 
 OSX_COMPAT=""
 DARWIN_VER=$(uname -r | cut -f 1 -d .)
@@ -44,6 +48,7 @@ function DoCodeSignMaybe { # ARGS: infoName fileOrDirName codesignIdentity
 cd $build_dir/../..
 
 VERSION=`git describe --tags`
+GIT_COMMIT_HASH=$(git rev-parse HEAD)
 
 # Paramterize
 BUILDDIR=/tmp/electrumabc-build
@@ -76,7 +81,7 @@ have_brew=`which brew`
 have_macports=`which port`
 if [ -n "$have_brew" ]; then
     info "Ensuring build prerequisites are installed via brew"
-    for a in autoconf automake coreutils gettext libtool openssl@1.1 readline sqlite3 xz zlib swig ; do
+    for a in autoconf automake coreutils gettext libtool openssl@1.1 pkgconfig readline sqlite3 xz zlib swig ; do
         brew list $a > /dev/null 2>&1
         if [ "$?" != "0" ]; then
             info "Installing $a"
@@ -136,8 +141,45 @@ python3 -m pip install -I --user -r contrib/osx/requirements-osx-build.txt \
     || fail "Could not install osx build requirements"
 
 
-info "Installing PyInstaller"
-python3 -m pip install pyinstaller==4.3 --user --upgrade && pyenv rehash || fail "Could not install PyInstaller"
+#info "Installing PyInstaller"
+#python3 -m pip install pyinstaller==4.3 --user --upgrade && pyenv rehash || fail "Could not install PyInstaller"
+
+info "Building PyInstaller."
+PYINSTALLER_REPO="https://github.com/pyinstaller/pyinstaller.git"
+PYINSTALLER_COMMIT="40c9abce2d8de879e414fd377c933dccaab1e156"
+# ^ tag "4.2"
+# TODO test newer versions of pyinstaller for build-reproducibility.
+#      we are using this version for now due to change in code-signing behaviour
+#      (https://github.com/pyinstaller/pyinstaller/pull/5581)
+(
+    if [ -f "$CACHEDIR/pyinstaller/PyInstaller/bootloader/Darwin-64bit/runw" ]; then
+        info "pyinstaller already built, skipping"
+        exit 0
+    fi
+    cd $build_dir/../..
+    ELECTRUM_COMMIT_HASH=$(git rev-parse HEAD)
+    cd "$CACHEDIR"
+    rm -rf pyinstaller
+    mkdir pyinstaller
+    cd pyinstaller
+    # Shallow clone
+    git init
+    git remote add origin $PYINSTALLER_REPO
+    git fetch --depth 1 origin $PYINSTALLER_COMMIT
+    git checkout -b pinned "${PYINSTALLER_COMMIT}^{commit}"
+    rm -fv PyInstaller/bootloader/Darwin-*/run* || true
+    # add reproducible randomness. this ensures we build a different bootloader for each commit.
+    # if we built the same one for all releases, that might also get anti-virus false positives
+    echo "const char *electrum_tag = \"tagged by $PACKAGE@$GIT_COMMIT_HASH\";" >> ./bootloader/src/pyi_main.c
+    pushd bootloader
+    # compile bootloader
+    python3 ./waf all CFLAGS="-static"
+    popd
+    # sanity check bootloader is there:
+    [[ -e "PyInstaller/bootloader/Darwin-64bit/runw" ]] || fail "Could not find runw in target dir!"
+) || fail "PyInstaller build failed"
+info "Installing PyInstaller."
+python3 -m pip install --no-build-isolation --no-dependencies --no-warn-script-location "$CACHEDIR/pyinstaller"
 
 info "Using these versions for building $PACKAGE:"  # NB: PACKAGE var comes from ../base.sh
 sw_vers
