[build] update requirements and scripts
- We updated the OSX build to no longer keep a separate
  requirements-binaries-osx.txt file, since OSX now has identical
  binary requirements as the other platforms.

diff --git a/contrib/osx/make_osx b/contrib/osx/make_osx
--- a/contrib/osx/make_osx
+++ b/contrib/osx/make_osx
@@ -6,12 +6,10 @@ test -n "$build_dir" -a -d "$build_dir" || (echo "Cannot determine build dir. FI
 . "$build_dir"/../base.sh # functions we use below
 
 OSX_COMPAT=""
-OSX_REQ_BIN="-osx"
 DARWIN_VER=$(uname -r | cut -f 1 -d .)
 if ((DARWIN_VER < 17)); then
     fail "Minimum OSX High Sierra is required to build"
 fi
-REQUIREMENTS_BINARIES="requirements-binaries${OSX_REQ_BIN}.txt"
 
 function DoCodeSignMaybe { # ARGS: infoName fileOrDirName codesignIdentity
     infoName="$1"
@@ -139,9 +137,7 @@ python3 -m pip install -I --user -r contrib/osx/requirements-osx-build.txt \
 
 
 info "Installing PyInstaller"
-# Pinpoint PyInstaller version 4.3 because PyInstaller 4.4 produces broken DMG files.
-# TODO: try removing the version pinpointing after PyInstaller is updated on PyPi.
-python3 -m pip install pyinstaller==4.3 --user --upgrade && pyenv rehash || fail "Could not install PyInstaller"
+python3 -m pip install pyinstaller --user --upgrade && pyenv rehash || fail "Could not install PyInstaller"
 
 info "Using these versions for building $PACKAGE:"  # NB: PACKAGE var comes from ../base.sh
 sw_vers
@@ -191,7 +187,7 @@ contrib/make_zlib && contrib/make_libevent && contrib/make_openssl && contrib/ma
 
 info "Installing requirements..."
 python3 -m pip install -r ./contrib/deterministic-build/requirements.txt --user || fail "Could not install requirements"
-python3 -m pip install -r ./contrib/deterministic-build/${REQUIREMENTS_BINARIES} --user || fail "Could not install binary requirements"
+python3 -m pip install -r ./contrib/deterministic-build/requirements-binaries.txt --user || fail "Could not install binary requirements"
 
 info "Installing hardware wallet requirements..."
 python3 -m pip install -r ./contrib/deterministic-build/requirements-hw.txt --user || \
